apiVersion: v1
kind: Service
metadata:
  name: platform-demo-svc
  namespace: platformdemo
spec:
  selector:
    app: platform-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
