name: CD - Deploy to AKS (dev)

on:
  workflow_run:
    workflows: ["CI - Build and Push Image to ACR"]
    types:
      - completed

permissions:
  contents: read

env:
  ACR_LOGIN_SERVER: acrplatformdemodev.azurecr.io
  IMAGE_NAME: platform-demo
  AKS_NAME: aks-platformdemo-dev
  RG_NAME: rg-platformdemo-dev
  NAMESPACE: platformdemo
  DEPLOYMENT: platform-demo
  CONTAINER: platform-demo

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Azure Login (CD Service Principal)
        uses: azure/login@v2
        with:
          creds: >
            {"clientId":"${{ secrets.AZURE_CD_CLIENT_ID }}",
             "clientSecret":"${{ secrets.AZURE_CD_CLIENT_SECRET }}",
             "tenantId":"${{ secrets.AZURE_CD_TENANT_ID }}",
             "subscriptionId":"${{ secrets.AZURE_CD_SUBSCRIPTION_ID }}"}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RG_NAME }}
          cluster-name: ${{ env.AKS_NAME }}

      - name: Deploy image built by CI (sha tag)
        run: |
          SHORT_SHA="${{ github.event.workflow_run.head_sha }}"
          SHORT_SHA="${SHORT_SHA::7}"
          NEW_IMAGE="${ACR_LOGIN_SERVER}/${IMAGE_NAME}:sha-${SHORT_SHA}"

          echo "Deploying image: $NEW_IMAGE"
          kubectl -n "$NAMESPACE" set image deployment/"$DEPLOYMENT" "$CONTAINER"="$NEW_IMAGE"
          kubectl -n "$NAMESPACE" rollout status deployment/"$DEPLOYMENT" --timeout=180s

      - name: Show pods
        run: kubectl get pods -n $NAMESPACE
