name: CI - Build and Push Image to ACR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  ACR_NAME: acrplatformdemodev
  ACR_LOGIN_SERVER: acrplatformdemodev.azurecr.io
  IMAGE_NAME: platform-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: >
            {"clientId":"${{ secrets.AZURE_CLIENT_ID }}",
             "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
             "tenantId":"${{ secrets.AZURE_TENANT_ID }}",
             "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker to ACR (via Azure CLI token)
        run: az acr login --name $ACR_NAME

      - name: Build and Push (linux/amd64)
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          docker buildx build \
            --platform linux/amd64 \
            -f docker/Dockerfile \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:sha-$SHORT_SHA \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest \
            --push .
